import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


// bootstrap

import 'bootstrap/dist/css/bootstrap-grid.css';
import { Container } from "react-bootstrap";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Container fluid>
        {children}
        </Container>
      </body>
    </html>
  );
}
